# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'
 pod 'ZXingObjC', '~>3.2.1'
 pod ‘Realm’, '~>2.3.0’

target 'MDW' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MDW

end
