# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'


target 'MDW' do

  # Pods for MDW
 
 pod 'ZXingObjC', '~>3.2.1'
 pod 'Realm', '~>2.3.0'
 pod 'Toast', '~> 3.1.0'
end
